# fly.toml app configuration file generated for nido-conviviality-production on 2023-11-25T18:19:48-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nido-conviviality-production"
primary_region = "ord"

[build]

[http_service]
  internal_port = 80
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
