#!/usr/bin/env python
from sqlalchemy import create_engine
from sqlalchemy.orm import Session

from nido_backend.db_models import DBCommunity, DBEmailContact, DBUser


def seed_db(db_session):
    communities = [
        DBCommunity(name="Schneider-Koch"),
        DBCommunity(name="Kassulke, Emard and MacGyver"),
        DBCommunity(name="Nolan-Shields"),
        DBCommunity(name="Bauch-Gerhold"),
        DBCommunity(name="Mohr Group"),
        DBCommunity(name="Turner, McDermott and Koch"),
        DBCommunity(name="Rogahn-Kulas"),
        DBCommunity(name="Powlowski-Kulas"),
        DBCommunity(name="Upton and Sons"),
        DBCommunity(name="Block, Morar and Hilpert"),
        DBCommunity(name="Kessler-Bradtke"),
        DBCommunity(name="Larson Group"),
        DBCommunity(name="Tromp, Gibson and Leffler"),
        DBCommunity(name="Simonis-Kulas"),
        DBCommunity(name="Spinka, Russel and Daniel"),
        DBCommunity(name="Romaguera, Lockman and Tromp"),
        DBCommunity(name="Kovacek, Cruickshank and Zboncak"),
        DBCommunity(name="Upton, Hyatt and Gorczany"),
        DBCommunity(name="Spinka-Macejkovic"),
        DBCommunity(name="Koch, Heller and Satterfield"),
        DBCommunity(name="Beahan, Mills and Botsford"),
        DBCommunity(name="Senger-Altenwerth"),
        DBCommunity(name="Lynch, Kling and Rippin"),
        DBCommunity(name="Cartwright Group"),
        DBCommunity(name="Thompson, Monahan and Schuppe"),
    ]

    users = [
        DBUser(community_id=10, personal_name="Marie-françoise", family_name="Cain"),
        DBUser(community_id=20, personal_name="Gérald", family_name="Maiden"),
        DBUser(community_id=14, personal_name="Táng", family_name="Chiverton"),
        DBUser(community_id=23, personal_name="Gérald", family_name="Jewell"),
        DBUser(community_id=22, personal_name="Eugénie", family_name="Vuitton"),
        DBUser(community_id=18, personal_name="Adélie", family_name="Willshire"),
        DBUser(community_id=12, personal_name="Océane", family_name="Childerhouse"),
        DBUser(community_id=25, personal_name="Faîtes", family_name="Habgood"),
        DBUser(community_id=22, personal_name="Zhì", family_name="Ballham"),
        DBUser(community_id=9, personal_name="Renée", family_name="Cooksey"),
        DBUser(community_id=12, personal_name="Björn", family_name="Crum"),
        DBUser(community_id=1, personal_name="Faîtes", family_name="Vice"),
        DBUser(community_id=5, personal_name="Göran", family_name="Boichat"),
        DBUser(community_id=15, personal_name="Tú", family_name="Tunny"),
        DBUser(community_id=23, personal_name="Eléa", family_name="Dittson"),
        DBUser(community_id=23, personal_name="Yénora", family_name="Emby"),
        DBUser(community_id=9, personal_name="Pénélope", family_name="Miskelly"),
        DBUser(community_id=5, personal_name="Aurélie", family_name="Charville"),
        DBUser(community_id=2, personal_name="Kévina", family_name="Lots"),
        DBUser(community_id=3, personal_name="Cinéma", family_name="Pigford"),
        DBUser(community_id=24, personal_name="Audréanne", family_name="Cords"),
        DBUser(community_id=20, personal_name="Andrée", family_name="Heck"),
        DBUser(community_id=9, personal_name="Léa", family_name="Rivitt"),
        DBUser(community_id=6, personal_name="Cinéma", family_name="Addinall"),
        DBUser(community_id=11, personal_name="Maïly", family_name="Fevers"),
        DBUser(community_id=18, personal_name="Alberik", family_name="Willgress"),
        DBUser(community_id=17, personal_name="Vincenz", family_name="Bernardoux"),
        DBUser(community_id=10, personal_name="Gian", family_name="Depper"),
        DBUser(community_id=1, personal_name="Windham", family_name="Leroux"),
        DBUser(community_id=15, personal_name="Kiley", family_name="Kanzler"),
        DBUser(community_id=9, personal_name="Ransom", family_name="Townby"),
        DBUser(community_id=16, personal_name="Joe", family_name="Iacovelli"),
        DBUser(community_id=9, personal_name="Morty", family_name="Crafter"),
        DBUser(community_id=9, personal_name="Ulrich", family_name="Slidders"),
        DBUser(community_id=12, personal_name="Skipp", family_name="Rawsen"),
        DBUser(community_id=2, personal_name="Reed", family_name="Doe"),
        DBUser(community_id=12, personal_name="Kincaid", family_name="Pellingar"),
        DBUser(community_id=15, personal_name="Isadore", family_name="Bayles"),
        DBUser(community_id=22, personal_name="Adler", family_name="Helsdon"),
        DBUser(community_id=3, personal_name="Maurizio", family_name="Blakely"),
        DBUser(community_id=16, personal_name="Guthry", family_name="Warsop"),
        DBUser(community_id=10, personal_name="Graeme", family_name="Henrique"),
        DBUser(community_id=19, personal_name="Alvie", family_name="Inglesant"),
        DBUser(community_id=9, personal_name="Phil", family_name="Itter"),
        DBUser(community_id=18, personal_name="Godwin", family_name="Ormrod"),
        DBUser(community_id=6, personal_name="Chico", family_name="Giacomuzzo"),
        DBUser(community_id=16, personal_name="Pooh", family_name="Brimelow"),
        DBUser(community_id=20, personal_name="Bentley", family_name="Blackhurst"),
        DBUser(community_id=10, personal_name="Zebedee", family_name="O'Towey"),
        DBUser(community_id=9, personal_name="Morey", family_name="Spalding"),
        DBUser(community_id=4, personal_name="Rockie", family_name="Orts"),
        DBUser(community_id=18, personal_name="Paxon", family_name="Akerman"),
        DBUser(community_id=9, personal_name="Micheil", family_name="Edler"),
        DBUser(community_id=11, personal_name="Wheeler", family_name="Dimberline"),
        DBUser(community_id=15, personal_name="Klemens", family_name="McGray"),
        DBUser(community_id=13, personal_name="Yul", family_name="Michie"),
        DBUser(community_id=12, personal_name="Weber", family_name="Rolley"),
        DBUser(community_id=10, personal_name="Ahmad", family_name="Habble"),
        DBUser(community_id=19, personal_name="Fabe", family_name="Olcot"),
        DBUser(community_id=19, personal_name="Hasheem", family_name="Shotton"),
        DBUser(community_id=11, personal_name="Dell", family_name="Kubyszek"),
        DBUser(community_id=25, personal_name="Reilly", family_name="Darrel"),
        DBUser(community_id=12, personal_name="Griffin", family_name="Arpin"),
        DBUser(community_id=3, personal_name="Forrest", family_name="Antonelli"),
        DBUser(community_id=23, personal_name="Ian", family_name="Eacott"),
        DBUser(community_id=12, personal_name="Salim", family_name="Suerz"),
        DBUser(community_id=7, personal_name="Shamus", family_name="Medcalfe"),
        DBUser(community_id=2, personal_name="Adamo", family_name="Connick"),
        DBUser(community_id=14, personal_name="Tucker", family_name="Kersey"),
        DBUser(community_id=19, personal_name="Cori", family_name="Hilliam"),
        DBUser(community_id=8, personal_name="Cassius", family_name="Arkow"),
        DBUser(community_id=14, personal_name="Jimmy", family_name="Choppen"),
        DBUser(community_id=24, personal_name="Lucas", family_name="McCarty"),
        DBUser(community_id=19, personal_name="Chip", family_name="Waszkiewicz"),
        DBUser(community_id=10, personal_name="Leicester", family_name="Solman"),
        DBUser(community_id=10, personal_name="Gregoire", family_name="Crotty"),
        DBUser(community_id=11, personal_name="Geneviève", family_name="Handley"),
        DBUser(community_id=19, personal_name="Simplifiés", family_name="Gabbitas"),
        DBUser(community_id=3, personal_name="Inès", family_name="Alen"),
        DBUser(community_id=8, personal_name="Frédérique", family_name="Makin"),
        DBUser(community_id=16, personal_name="Märta", family_name="Whether"),
        DBUser(community_id=18, personal_name="Annotés", family_name="Farlamb"),
        DBUser(community_id=10, personal_name="Liè", family_name="Corns"),
        DBUser(community_id=24, personal_name="Maï", family_name="Chelam"),
        DBUser(community_id=1, personal_name="Maïlys", family_name="Whittock"),
        DBUser(community_id=17, personal_name="Adèle", family_name="Janczyk"),
        DBUser(community_id=8, personal_name="Marie-noël", family_name="Marcroft"),
        DBUser(community_id=22, personal_name="Andréa", family_name="Elwyn"),
        DBUser(community_id=13, personal_name="Mélissandre", family_name="Goult"),
        DBUser(community_id=3, personal_name="Céline", family_name="Magson"),
        DBUser(community_id=3, personal_name="Inès", family_name="Tiron"),
        DBUser(community_id=11, personal_name="Laurélie", family_name="Ziehms"),
        DBUser(community_id=1, personal_name="Magdalène", family_name="Venes"),
        DBUser(community_id=12, personal_name="Adèle", family_name="Leades"),
        DBUser(community_id=20, personal_name="Hélèna", family_name="Pitford"),
        DBUser(community_id=3, personal_name="Andrée", family_name="Aizikov"),
        DBUser(community_id=19, personal_name="Håkan", family_name="Sextie"),
        DBUser(community_id=19, personal_name="Cloé", family_name="Lennarde"),
        DBUser(community_id=16, personal_name="Håkan", family_name="Itzchaky"),
        DBUser(community_id=2, personal_name="Véronique", family_name="Westman"),
    ]
    contact_methods = [
        DBEmailContact(user_id=1, email="ccaban0@google.co.jp"),
        DBEmailContact(user_id=2, email="dzealy1@pcworld.com"),
        DBEmailContact(user_id=3, email="corneles2@globo.com"),
        DBEmailContact(user_id=4, email="tbellchamber3@live.com"),
        DBEmailContact(user_id=5, email="eseaton4@google.pl"),
        DBEmailContact(user_id=6, email="cmaughan5@geocities.jp"),
        DBEmailContact(user_id=7, email="jkitchingman6@sun.com"),
        DBEmailContact(user_id=8, email="awilloway7@shareasale.com"),
        DBEmailContact(user_id=9, email="btildesley8@behance.net"),
        DBEmailContact(user_id=10, email="acolleford9@elpais.com"),
        DBEmailContact(user_id=11, email="lbanasevicha@soup.io"),
        DBEmailContact(user_id=12, email="dshavesb@lulu.com"),
        DBEmailContact(user_id=13, email="wodriscollc@apache.org"),
        DBEmailContact(user_id=14, email="jmaccafferkyd@mediafire.com"),
        DBEmailContact(user_id=15, email="ghumpatche@bravesites.com"),
        DBEmailContact(user_id=16, email="lbelchamf@theatlantic.com"),
        DBEmailContact(user_id=17, email="bjacquemeg@seattletimes.com"),
        DBEmailContact(user_id=18, email="hhauxwellh@auda.org.au"),
        DBEmailContact(user_id=19, email="mstartoni@reverbnation.com"),
        DBEmailContact(user_id=20, email="efolkerj@dropbox.com"),
        DBEmailContact(user_id=21, email="gmcgettigank@simplemachines.org"),
        DBEmailContact(user_id=22, email="bbelliardl@feedburner.com"),
        DBEmailContact(user_id=23, email="gvedyashkinm@amazonaws.com"),
        DBEmailContact(user_id=24, email="odankon@cpanel.net"),
        DBEmailContact(user_id=25, email="tcotsfordo@dropbox.com"),
        DBEmailContact(user_id=26, email="asouthworthp@springer.com"),
        DBEmailContact(user_id=27, email="cpallasq@sbwire.com"),
        DBEmailContact(user_id=28, email="phartshorner@bbc.co.uk"),
        DBEmailContact(user_id=29, email="fshevelss@prlog.org"),
        DBEmailContact(user_id=30, email="wredfernet@so-net.ne.jp"),
        DBEmailContact(user_id=31, email="cbaudtsu@chron.com"),
        DBEmailContact(user_id=32, email="ahuckellv@dedecms.com"),
        DBEmailContact(user_id=33, email="ameldrumw@kickstarter.com"),
        DBEmailContact(user_id=34, email="kkryzhovx@bizjournals.com"),
        DBEmailContact(user_id=35, email="gseckomy@phoca.cz"),
        DBEmailContact(user_id=36, email="rbruntjenz@indiegogo.com"),
        DBEmailContact(user_id=37, email="dflacknoe10@multiply.com"),
        DBEmailContact(user_id=38, email="cbebbington11@ezinearticles.com"),
        DBEmailContact(user_id=39, email="ccoggon12@loc.gov"),
        DBEmailContact(user_id=40, email="mtranfield13@marriott.com"),
        DBEmailContact(user_id=41, email="aciobutaro14@mtv.com"),
        DBEmailContact(user_id=42, email="ccrambie15@hp.com"),
        DBEmailContact(user_id=43, email="msnelman16@msu.edu"),
        DBEmailContact(user_id=44, email="gshasnan17@adobe.com"),
        DBEmailContact(user_id=45, email="atolman18@cafepress.com"),
        DBEmailContact(user_id=46, email="wculverhouse19@blogtalkradio.com"),
        DBEmailContact(user_id=47, email="aboyall1a@techcrunch.com"),
        DBEmailContact(user_id=48, email="smorigan1b@umich.edu"),
        DBEmailContact(user_id=49, email="fberthelet1c@unesco.org"),
        DBEmailContact(user_id=50, email="dkinforth1d@ft.com"),
        DBEmailContact(user_id=51, email="edrinkwater1e@artisteer.com"),
        DBEmailContact(user_id=52, email="mimort1f@yolasite.com"),
        DBEmailContact(user_id=53, email="bwoodford1g@webmd.com"),
        DBEmailContact(user_id=54, email="rlumbers1h@paypal.com"),
        DBEmailContact(user_id=55, email="bwhitmarsh1i@archive.org"),
        DBEmailContact(user_id=56, email="lhaggarth1j@mayoclinic.com"),
        DBEmailContact(user_id=57, email="cwhetton1k@wikispaces.com"),
        DBEmailContact(user_id=58, email="jpashan1l@t.co"),
        DBEmailContact(user_id=59, email="mkyrkeman1m@stanford.edu"),
        DBEmailContact(user_id=60, email="bmichin1n@businessweek.com"),
        DBEmailContact(user_id=61, email="ddalley1o@mayoclinic.com"),
        DBEmailContact(user_id=62, email="alesurf1p@edublogs.org"),
        DBEmailContact(user_id=63, email="byexley1q@un.org"),
        DBEmailContact(user_id=64, email="mvondrasek1r@engadget.com"),
        DBEmailContact(user_id=65, email="ggrioli1s@biglobe.ne.jp"),
        DBEmailContact(user_id=66, email="cbarehead1t@theatlantic.com"),
        DBEmailContact(user_id=67, email="mflawn1u@freewebs.com"),
        DBEmailContact(user_id=68, email="hgriffitts1v@joomla.org"),
        DBEmailContact(user_id=69, email="rvallance1w@ftc.gov"),
        DBEmailContact(user_id=70, email="clithcow1x@list-manage.com"),
        DBEmailContact(user_id=71, email="aianilli1y@studiopress.com"),
        DBEmailContact(user_id=72, email="wswallow1z@gizmodo.com"),
        DBEmailContact(user_id=73, email="hmuzzall20@un.org"),
        DBEmailContact(user_id=74, email="lgianilli21@dedecms.com"),
        DBEmailContact(user_id=75, email="wwolford22@artisteer.com"),
        DBEmailContact(user_id=76, email="sflew23@smugmug.com"),
        DBEmailContact(user_id=77, email="sratlee24@skyrock.com"),
        DBEmailContact(user_id=78, email="fmarrington25@histats.com"),
        DBEmailContact(user_id=79, email="dbalharry26@ovh.net"),
        DBEmailContact(user_id=80, email="dlilleyman27@slideshare.net"),
        DBEmailContact(user_id=81, email="tmccrudden28@yahoo.co.jp"),
        DBEmailContact(user_id=82, email="dtarpey29@ebay.co.uk"),
        DBEmailContact(user_id=83, email="tsheraton2a@slashdot.org"),
        DBEmailContact(user_id=84, email="ccarnelley2b@mac.com"),
        DBEmailContact(user_id=85, email="kfinnes2c@oakley.com"),
        DBEmailContact(user_id=86, email="kstave2d@cisco.com"),
        DBEmailContact(user_id=87, email="mbeevens2e@ihg.com"),
        DBEmailContact(user_id=88, email="epurselow2f@behance.net"),
        DBEmailContact(user_id=89, email="kokennavain2g@blinklist.com"),
        DBEmailContact(user_id=90, email="maynscombe2h@naver.com"),
        DBEmailContact(user_id=91, email="ebatey2i@comsenz.com"),
        DBEmailContact(user_id=92, email="slanglois2j@elegantthemes.com"),
        DBEmailContact(user_id=93, email="siskower2k@dagondesign.com"),
        DBEmailContact(user_id=94, email="dmaben2l@samsung.com"),
        DBEmailContact(user_id=95, email="mconman2m@ebay.co.uk"),
        DBEmailContact(user_id=96, email="sdubbin2n@wix.com"),
        DBEmailContact(user_id=97, email="rroseveare2o@hexun.com"),
        DBEmailContact(user_id=98, email="aalderman2p@washingtonpost.com"),
        DBEmailContact(user_id=99, email="rhorsley2q@comsenz.com"),
        DBEmailContact(user_id=100, email="lmegroff2r@thetimes.co.uk"),
    ]

    for c in communities:
        db_session.add(c)
    for u in users:
        db_session.add(u)
    for cm in contact_methods:
        db_session.add(cm)
    db_session.commit()


if __name__ == "__main__":
    import os

    from sqlalchemy import create_engine
    from sqlalchemy.orm import Session

    from nido_backend.db_models import Base

    engine = create_engine(os.environ["DATABASE_URL"])
    with Session(engine) as db_session:
        Base.metadata.create_all(bind=db_session.get_bind())
        seed_db(db_session)
